### ISSUE TITLE
Create Rest Endpoint for adding and getting words

### ISSUE THREAD

**Issue by annazarubina** [annazarubina/brainheap-back#1]
Create service with REST API, which can process HTTP requests:

- add new words (method POST)
- get all saved words (method GET)

Request path: /heap

Have to include UNIT/Component tests

**Comment by php-coder** [comment]
> Request path: /heap

Why not `/words` BTW?

**Comment by php-coder** [comment]
@annazarubina Did you know that you may mention the issue in the commit messages and related commits will appear on the issue page?
