### ISSUE TITLE
Get rid of toList() usage by returning List<> from repository

### ISSUE THREAD

**Issue by php-coder** [annazarubina/brainheap-back#17]
`repository.findAll().toList()` could be simplified into `repository.findAll()` if we modify repositories to return `List<T>` instead of `Iterable<T>`. It also reduces number of memory allocations and garbage.

CC @annazarubina

**Comment by php-coder** [comment]
A few occurrences are still there:
```console
$ git grep toList
src/main/kotlin/brainheap/item/rest/ItemController.kt:        return ResponseEntity(repository.findAll().toList(), HttpStatus.OK)
src/main/kotlin/brainheap/user/rest/UserController.kt:        return ResponseEntity(repository.findAll().toList(), HttpStatus.OK)
```

**Comment by annazarubina** [comment]
Can survive with it :)
