### ISSUE TITLE
Build Application on CI 

### ISSUE THREAD

**Issue by annazarubina** [annazarubina/brainheap-back#3]
As CI let's use Travis CI.

As a build tool, let's use Gradle.

**Comment by php-coder** [comment]
1) The tutorial and overview: https://docs.travis-ci.com/user/tutorial/
2) Java+Gradle configuration: https://docs.travis-ci.com/user/languages/java/
3) Database setup: https://docs.travis-ci.com/user/database-setup/

**Comment by innulic** [comment]
fix #3
