### ISSUE TITLE
Deploy Application on Server

### ISSUE THREAD

**Issue by annazarubina** [annazarubina/brainheap-back#4]
Deploy kotlin application on heroku

**Comment by php-coder** [comment]
Related: https://docs.travis-ci.com/user/deployment/script/

**Comment by php-coder** [comment]
Or for Heroku: https://docs.travis-ci.com/user/deployment/heroku/

**Comment by php-coder** [comment]
Another option is completely Docker-specific:
1) we can configure DockerHub to build an image after every push to GitHub (see https://docs.docker.com/docker-hub/builds/)
2) https://hub.docker.com/r/v2tec/watchtower/ could be run on a server to watch for a new images on DockerHub and pull/run a newer version when it's available
